services:
  - type: web
    name: betsageai
    env: python
    buildCommand: |
      cd bot_project && pip install -r requirements.txt
    startCommand: |
      cd bot_project && python -m app.main
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: SCRAPING_API_KEY
        value: your_scraping_api_key_here
      - key: SCRAPING_BASE_URL
        value: https://api.the-odds-api.com/v4/sports
    plan: free
    region: oregon
