services:
  - type: worker  # Use "web" if your bot uses a web server (e.g., for webhooks)
    name: sports-bot-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m app.main"  # Adjust if your entrypoint differs
    python:
      version: 3.9.13  # Match your Python version
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
